"""Core data models.

The shape of `Match` is the contract between generation (phase 2), verification
(phase 3), and evaluation (phase 4) — change it and all three move together.
"""

from __future__ import annotations

from enum import IntEnum, StrEnum

from pydantic import BaseModel, Field, field_validator


class PriceTier(IntEnum):
    """Cost relative to local alternatives in the same category, not absolute."""

    BUDGET = 1
    MODERATE = 2
    UPSCALE = 3
    LUXURY = 4


class Reach(StrEnum):
    """How far a place's footprint extends.

    The distinction that matters most is LOCAL/REGIONAL vs NATIONAL: a chain
    present in both cities is a boring answer, however well it matches on
    every other dimension.
    """

    LOCAL = "local"  # single city or metro
    REGIONAL = "regional"  # multi-city, identified with a region
    NATIONAL = "national"  # present nationwide


class RoleTag(BaseModel):
    """One entry in the role vocabulary."""

    id: str = Field(description="Stable snake_case identifier")
    definition: str = Field(description="What role this place plays in local life")
    exemplars: list[str] = Field(
        default_factory=list,
        description="2-3 known instances, formatted 'Name (City)'",
    )

    @field_validator("id")
    @classmethod
    def _snake_case(cls, v: str) -> str:
        if not v.replace("_", "").isalnum() or v != v.lower():
            raise ValueError(f"role id must be lowercase snake_case, got {v!r}")
        return v


class Place(BaseModel):
    """A named institution in a city. The unit of both query and answer."""

    name: str
    city: str = Field(description="Slug, e.g. 'austin'")
    category: str = Field(description="Coarse bucket, e.g. 'grocery', 'gym'")
    aliases: list[str] = Field(
        default_factory=list,
        description="How people actually type it: 'HEB', HEB grocery'",
    )
    fsq_place_id: str | None = Field(
        default=None,
        description="Foursquare OS Places ID; None when unmatched in the dataset",
    )
    notes: str | None = None


class Candidate(BaseModel):
    """One proposed equivalent, as generated by the model."""

    name: str
    reasoning: str = Field(
        description="Why this place fills the same role. Surfaced to the user — "
        "the explanation is the product, a bare name is unsatisfying."
    )
    confidence: float = Field(ge=0.0, le=1.0)

    # Populated by phase 3, not by the model.
    fsq_place_id: str | None = None
    verified: bool | None = Field(
        default=None,
        description="None = not yet checked. False is a flag, not a filter — "
        "Foursquare coverage of small local businesses is uneven.",
    )
    verification_note: str | None = None


class Match(BaseModel):
    """A source place, its role profile, and ranked equivalents in a target city."""

    source: Place
    target_city: str
    role_tags: list[str] = Field(description="Role ids from the taxonomy, most defining first")
    price_tier: PriceTier
    reach: Reach
    candidates: list[Candidate] = Field(description="Ranked best-first")

    def top(self) -> Candidate | None:
        return self.candidates[0] if self.candidates else None


class GroundTruthPair(BaseModel):
    """A human-sourced answer, mined from locals and hand-cleaned.

    `accepted` holds multiple answers on purpose. When locals disagree about
    the Chicago H-E-B, that disagreement is signal about the role being
    genuinely contested — not noise to average away.
    """

    source_name: str
    source_city: str
    target_city: str
    accepted: list[str] = Field(min_length=1)
    source_url: str | None = None
    note: str | None = None
